### ISSUE TITLE
I can’t install

### ISSUE THREAD

**Issue by gisadan** [parkr/ruby-build-github#8]
ihyeonsuui-MacBook-Pro:~ HSLee$ git clone git://github.com/parkr/ruby-build-github.git "$(rbenv root)/plugins/ruby-build-github"
-bash: rbenv: command not found
fatal: could not create leading directories of '/plugins/ruby-build-github': Permission denied

?? how I ??

**Comment by parkr** [comment]
Check out the instructions here: https://github.com/sstephenson/rbenv#table-of-contents
